#ifndef STACK_H_
#define STACK_H_

#define MIN_STACK_SIZE 64
#define MAX_STACK_SIZE 128

#define TOTAL_RAM_SIZE (RAMEND - RAMSTART)

#define CANARY_VALUE 0XDEADBEEF

#define MAX_NUM_THREADS 8

#ifdef __ASSEMBLER__
  #define STACK_CAST(x) (x)
#else
  #define STACK_CAST(x) ((uint8_t*)x)
#endif

#define THREAD0_STACK_BASE STACK_CAST(RAMEND)
#define THREAD1_STACK_BASE STACK_CAST(THREAD0_STACK_BASE - THREAD0_STACK_SIZE)
#define THREAD2_STACK_BASE STACK_CAST(RAMEND)
#define THREAD3_STACK_BASE STACK_CAST(RAMEND)
#define THREAD4_STACK_BASE STACK_CAST(RAMEND)
#define THREAD5_STACK_BASE STACK_CAST(RAMEND)
#define THREAD6_STACK_BASE STACK_CAST(RAMEND)
#define THREAD7_STACK_BASE STACK_CAST(RAMEND)



#endif /* STACK_H_ */